name: terraform plan

on: workflow_dispatch

jobs: 
  terraform-plan:
    runs-on: ubuntu_latest
    steps:
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        run: terraform init