name: terraform plan

on: workflow_dispatch

jobs: 
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        run: terraform init
        
      - name: terrform plan
        run: terraform plan