name: example

on: workflow_dispatch

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: terraform install
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        run: terraform init
